import { useEffect, useMemo, useState } from "react";
import "./importer-pro.css";

function emptyForm(){return{customs_record_id:"",title:"",due_date:new Date().toISOString().slice(0,10),priority:"NORMAL",notes:""};}
function dayKey(value){return value ? String(value).slice(0,10) : "";}

export default function ImporterProRemindersPage({supabase,organizationId,userId}){
  const [records,setRecords]=useState([]);const[items,setItems]=useState([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[showForm,setShowForm]=useState(false);const[form,setForm]=useState(emptyForm());
  async function loadData(){if(!organizationId)return;setLoading(true);setError("");try{const[{data:r,error:re},{data:i,error:ie}]=await Promise.all([supabase.from("importer_customs_records").select("id,vehicle,vin").eq("organization_id",organizationId).order("created_at",{ascending:false}),supabase.from("importer_customs_reminders").select("*").eq("organization_id",organizationId).order("due_date",{ascending:true})]);if(re)throw re;if(ie)throw ie;setRecords(Array.isArray(r)?r:[]);setItems(Array.isArray(i)?i:[]);}catch(err){console.error("V39.7.5 PRO REMINDERS ERROR:",err);setError(err?.message||"No fue posible cargar los recordatorios.");}finally{setLoading(false);}}
  useEffect(()=>{loadData();},[organizationId]);
  const today=new Date().toISOString().slice(0,10);const stats=useMemo(()=>({overdue:items.filter(i=>i.status==="PENDING"&&dayKey(i.due_date)<today).length,today:items.filter(i=>i.status==="PENDING"&&dayKey(i.due_date)===today).length,pending:items.filter(i=>i.status==="PENDING").length,done:items.filter(i=>i.status==="DONE").length}),[items,today]);
  const recordMap=useMemo(()=>new Map(records.map(r=>[r.id,r])),[records]);
  async function saveReminder(e){e.preventDefault();if(!form.title.trim()){setError("Escribí el recordatorio.");return;}setSaving(true);setError("");try{const{error:ie}=await supabase.from("importer_customs_reminders").insert({organization_id:organizationId,customs_record_id:form.customs_record_id||null,title:form.title.trim(),due_date:form.due_date||null,priority:form.priority,notes:form.notes.trim()||null,status:"PENDING",created_by:userId,updated_by:userId});if(ie)throw ie;setShowForm(false);setForm(emptyForm());setMessage("Recordatorio creado.");await loadData();}catch(err){setError(err?.message||"No fue posible guardar el recordatorio.");}finally{setSaving(false);}}
  async function toggleDone(item){setError("");const next=item.status==="DONE"?"PENDING":"DONE";const{error:ue}=await supabase.from("importer_customs_reminders").update({status:next,completed_at:next==="DONE"?new Date().toISOString():null,updated_by:userId,updated_at:new Date().toISOString()}).eq("id",item.id).eq("organization_id",organizationId);if(ue){setError(ue.message);return;}await loadData();}
  return <section className="importer-pro-page"><header className="importer-pro-hero"><div><span>IMPORTADOR PRO · AGENDA</span><h1>Recordatorios</h1><p>No perdás fechas de IVA, selectivo, documentos, pagos o seguimientos con tu gestor.</p></div><button className="pro-primary" onClick={()=>setShowForm(true)}>＋ Nuevo recordatorio</button></header>
  <section className="importer-pro-kpis four"><article className={stats.overdue?"danger":""}><small>VENCIDOS</small><strong>{stats.overdue}</strong><span>Requieren atención</span></article><article><small>PARA HOY</small><strong>{stats.today}</strong><span>Vencen hoy</span></article><article><small>PENDIENTES</small><strong>{stats.pending}</strong><span>Agenda activa</span></article><article className="highlight"><small>COMPLETADOS</small><strong>{stats.done}</strong><span>Historial resuelto</span></article></section>
  {message&&<div className="pro-message success">{message}</div>}{error&&<div className="pro-message error">{error}</div>}
  <section className="importer-pro-card"><div className="pro-card-head"><div><small>AGENDA PRO</small><h2>Próximos pendientes</h2></div><button onClick={loadData}>↻ Actualizar</button></div>{loading?<div className="pro-empty">Cargando agenda...</div>:items.length===0?<div className="pro-empty"><span>🔔</span><strong>Tu agenda está limpia.</strong><p>Creá recordatorios para fechas importantes de tus gestiones.</p></div>:<div className="pro-reminder-list">{items.map(item=>{const record=recordMap.get(item.customs_record_id);const overdue=item.status==="PENDING"&&dayKey(item.due_date)<today;return <article key={item.id} className={`${item.status==="DONE"?"done":""} ${overdue?"overdue":""}`}><button className="pro-check" onClick={()=>toggleDone(item)}>{item.status==="DONE"?"✓":""}</button><div><strong>{item.title}</strong><span>{record?.vehicle||"Recordatorio general"}{record?.vin?` · ${record.vin}`:""}</span>{item.notes&&<small>{item.notes}</small>}</div><div className="pro-reminder-date"><small>{item.priority}</small><strong>{item.due_date?new Date(`${dayKey(item.due_date)}T12:00:00`).toLocaleDateString("es-GT"):"Sin fecha"}</strong></div></article>;})}</div>}</section>
  {showForm&&<div className="pro-modal-backdrop" onMouseDown={(e)=>{if(e.target===e.currentTarget&&!saving)setShowForm(false);}}><form className="pro-modal" onSubmit={saveReminder}><div className="pro-modal-head"><div><small>AGENDA PRO</small><h2>Nuevo recordatorio</h2></div><button type="button" onClick={()=>setShowForm(false)}>×</button></div><div className="pro-form-grid"><label className="span-2"><span>Recordatorio *</span><input required value={form.title} onChange={(e)=>setForm(p=>({...p,title:e.target.value}))} placeholder="Ej. Confirmar pago de IVA"/></label><label className="span-2"><span>Gestión relacionada</span><select value={form.customs_record_id} onChange={(e)=>setForm(p=>({...p,customs_record_id:e.target.value}))}><option value="">— Recordatorio general —</option>{records.map(r=><option key={r.id} value={r.id}>{r.vehicle}{r.vin?` · ${r.vin}`:""}</option>)}</select></label><label><span>Fecha</span><input type="date" value={form.due_date} onChange={(e)=>setForm(p=>({...p,due_date:e.target.value}))}/></label><label><span>Prioridad</span><select value={form.priority} onChange={(e)=>setForm(p=>({...p,priority:e.target.value}))}><option value="BAJA">Baja</option><option value="NORMAL">Normal</option><option value="ALTA">Alta</option><option value="URGENTE">Urgente</option></select></label><label className="span-2"><span>Notas</span><textarea rows="3" value={form.notes} onChange={(e)=>setForm(p=>({...p,notes:e.target.value}))}/></label></div><div className="pro-modal-actions"><button type="button" onClick={()=>setShowForm(false)}>Cancelar</button><button className="pro-primary" disabled={saving}>{saving?"Guardando...":"Crear recordatorio"}</button></div></form></div>}
  </section>;
}
